/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import TopPage from "../components/topPage";

export default function Home({ posts }) {
    return (
        <TopPage>
            <Head>
                <title>Madison Funderburk</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="profile-section">
                <img
                    src="/images/pfp.jpg"
                    alt="A picture of me looking dapper!"
                />
                <h1>Hey! I'm Madison.</h1>
                <h2>I'm a programmer</h2>
                <p>
                    I've got a lot of projects in mind and I'm going to start
                    building them and posting them here. Machine learning,
                    back-end development, a11y design, and all sorts of other
                    topics interest me.
                </p>
            </div>
        </TopPage>
    );
}
