/* eslint-disable react/no-unescaped-entities */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import TopPage from "../components/topPage";

export default function Home({ posts }) {
    return (
        <TopPage>
            <Head>
                <title>Madison Funderburk</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="profile-section">
                <img
                    src="/images/pfp.jpg"
                    alt="A picture of me looking dapper!"
                />
                <h1>Hey! I'm Madison.</h1>
                <h2>I'm a programmer</h2>
                <p>
                    As a self taught programmer, I find that I'm constantly on
                    the search for something new to teach myself. I'm eager to
                    tackle complex challenges, and I'm always working towards
                    mastering the intersection of math and computer science! I'm
                    trying my hand at machine learning, and want to share the
                    process with you through concise posts with clear
                    explanations and practical tips. So join me and let's learn
                    together!
                </p>
            </div>
        </TopPage>
    );
}
